name: ParaBank Automated Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
      
    - name: Run ParaBank Tests
      run: npm test
      env:
        BROWSER: ${{ matrix.browser }}
        CI: true
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.browser }}
        path: |
          test-results/
          screenshots/
          test-report.html
        retention-days: 7
        
    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: html-report-${{ matrix.browser }}
        path: test-report.html
        retention-days: 7

  report:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        
    - name: Generate consolidated report
      run: |
        mkdir -p consolidated-report
        echo '<!DOCTYPE html>' > consolidated-report/index.html
        echo '<html><head><title>ParaBank Test Results - All Browsers</title>' >> consolidated-report/index.html
        echo '<style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; }
        .header { text-align: center; border-bottom: 3px solid #2196F3; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #2196F3; margin: 0; }
        .browser-section { margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
        .browser-header { background: #2196F3; color: white; padding: 10px 15px; margin: -20px -20px 15px -20px; border-radius: 8px 8px 0 0; }
        .status-pass { color: #4CAF50; font-weight: bold; }
        .status-fail { color: #f44336; font-weight: bold; }
        .artifact-link { display: inline-block; margin: 5px 10px; padding: 8px 15px; background: #2196F3; color: white; text-decoration: none; border-radius: 4px; }
        .artifact-link:hover { background: #1976D2; }
        </style></head><body>' >> consolidated-report/index.html
        echo '<div class="container">' >> consolidated-report/index.html
        echo '<div class="header"><h1>ParaBank CI/CD Test Results</h1>' >> consolidated-report/index.html
        echo '<p>Pipeline executed on: '$(date)' UTC</p>' >> consolidated-report/index.html
        echo '<p>Commit: ${{ github.sha }}</p></div>' >> consolidated-report/index.html
        
        # Check for browser-specific reports
        for browser in chromium firefox webkit; do
          echo '<div class="browser-section">' >> consolidated-report/index.html
          echo '<div class="browser-header"><h2>'$browser' Results</h2></div>' >> consolidated-report/index.html
          
          if [ -d "artifacts/html-report-$browser" ]; then
            echo '<p class="status-pass">✓ Tests executed successfully</p>' >> consolidated-report/index.html
            echo '<a href="../artifacts/html-report-'$browser'/test-report.html" class="artifact-link">View '$browser' Report</a>' >> consolidated-report/index.html
          else
            echo '<p class="status-fail">✗ Tests failed or artifacts missing</p>' >> consolidated-report/index.html
          fi
          
          if [ -d "artifacts/test-results-$browser" ]; then
            echo '<a href="../artifacts/test-results-'$browser'/" class="artifact-link">View '$browser' Artifacts</a>' >> consolidated-report/index.html
          fi
          
          echo '</div>' >> consolidated-report/index.html
        done
        
        echo '</div></body></html>' >> consolidated-report/index.html
        
    - name: Upload consolidated report
      uses: actions/upload-artifact@v4
      with:
        name: consolidated-test-report
        path: consolidated-report/
        retention-days: 30
        
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let comment = '## 🎯 ParaBank Test Results\n\n';
          comment += '| Browser | Status | Report |\n';
          comment += '|---------|--------|--------|\n';
          
          const browsers = ['chromium', 'firefox', 'webkit'];
          for (const browser of browsers) {
            const artifactPath = `artifacts/html-report-${browser}`;
            if (fs.existsSync(artifactPath)) {
              comment += `| ${browser} | ✅ PASSED | [View Report](${context.payload.pull_request.html_url}/checks) |\n`;
            } else {
              comment += `| ${browser} | ❌ FAILED | [View Logs](${context.payload.pull_request.html_url}/checks) |\n`;
            }
          }
          
          comment += '\n📊 [View Consolidated Report](${context.payload.pull_request.html_url}/checks)\n';
          comment += '\n🔍 **Test Details:**\n';
          comment += '- **TC 001**: Customer Registration\n';
          comment += '- **TC 002**: User Login Functionality\n';
          comment += `\n⏰ Executed at: ${new Date().toISOString()}`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });